(()=>{
const API='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-fichajes/api/';
let token=localStorage.getItem('efs_token')||'', me=null, dayCursor=new Date(), monthCursor=new Date(), calCursor=new Date(), activeTab='Today', selectedDate='';
const q=id=>document.getElementById(id), qa=s=>[...document.querySelectorAll(s)], pad=n=>String(n).padStart(2,'0');
const iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0), fmt=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):String(Math.round(n*100)/100).replace('.',',')};
function showMsg(id,t,ok=false){const e=q(id);e.textContent=t||'';e.className='msg '+(t?(ok?'ok':'error'):'')}
async function api(path,body={}){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({ok:false,error:'Respuesta no válida'}));if(!r.ok&&j.ok!==false)j.ok=false;return j}catch{return {ok:false,error:'Sin conexión'}}}
async function entries(a,b,employee=null){const r=await api('entries',{p_session_token:token,p_start_date:a,p_end_date:b,p_employee_id:employee});if(!r.ok)throw new Error(r.error||'No se pudieron cargar las horas');return r.entries||[]}
function payrollBounds(y,m){return [new Date(y,m-1,21),new Date(y,m,20)]}
function monthBounds(y,m){return [new Date(y,m,1),new Date(y,m+1,0)]}
function sums(arr){return arr.reduce((o,e)=>{o.n+=num(e.normal);o.e+=num(e.extra);o.h+=num(e.holiday);o.p+=num(e.personal);if(e.incident==='vacation')o.v++;if(e.incident==='sick_leave')o.s++;return o},{n:0,e:0,h:0,p:0,v:0,s:0})}
function workLabel(d){const wd=d.getDay();return wd===0||wd===6?'FIN DE SEMANA · SOLO HORAS FESTIVAS':'DÍA LABORABLE'}
function displayIncident(v){return ({vacation:'Vacaciones',sick_leave:'Baja / IT',absence:'Ausencia',personal:'Personal'})[v]||'Ninguna'}
function hourCard(key,label,value){return `<div class="hourCard"><div class="hourLabel">${label}</div><div class="hourNum" data-num="${key}">${fmt(value)}</div><div class="hourControls"><button data-step="${key}" data-delta="-0.25">−</button><button data-step="${key}" data-delta="0.25">+</button></div><input type="hidden" data-field="${key}" value="${num(value)}"></div>`}
function formHTML(e={}){return `${hourCard('normal','NORMALES',e.normal)}${hourCard('extra','EXTRA',e.extra)}${hourCard('holiday','FESTIVAS',e.holiday)}${hourCard('personal','PERSONALES',e.personal)}`}
function bindSteppers(root){root.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const k=b.dataset.step, inp=root.querySelector(`[data-field=${k}]`), val=Math.max(0,num(inp.value)+num(b.dataset.delta));inp.value=Math.round(val*100)/100;root.querySelector(`[data-num=${k}]`).textContent=fmt(val)})}
function editorFields(e={}){return `<div class="hourGrid">${formHTML(e)}</div><div class="workSection"><div class="sectionTitle">Trabajo e incidencias</div><div class="fieldBlock fieldWrap"><div class="fieldLabel">INCIDENCIA</div><select data-field="incident"><option value="">Ninguna</option><option value="vacation">Vacaciones</option><option value="sick_leave">Baja / IT</option><option value="absence">Ausencia</option><option value="personal">Personal</option></select></div><div class="fieldBlock fieldWrap"><div class="fieldLabel">OBRA</div><input data-field="worksite" value="${esc(e.worksite||'')}" placeholder="Obra o cliente"></div><div class="fieldBlock fieldWrap"><div class="fieldLabel">OBSERVACIONES</div><textarea data-field="notes" placeholder="Observaciones">${esc(e.notes||'')}</textarea></div><div class="saveRow"><button data-action="save" class="primaryBtn">GUARDAR</button><button data-action="clear" class="secondaryBtn">BORRAR DÍA</button></div><div data-field="msg" class="msg"></div></div>`}
function valuesFrom(root){const g=k=>root.querySelector(`[data-field=${k}]`);return {normal:num(g('normal').value),extra:num(g('extra').value),holiday:num(g('holiday').value),personal:num(g('personal').value),incident:g('incident').value||null,worksite:g('worksite').value,notes:g('notes').value}}
async function saveDate(date,root){const out=root.querySelector('[data-field=msg]'),v=valuesFrom(root);out.textContent='Guardando…';out.className='msg';const r=await api('save',{p_session_token:token,p_work_date:date,p_normal:v.normal,p_extra:v.extra,p_holiday:v.holiday,p_personal:v.personal,p_worksite:v.worksite,p_incident:v.incident,p_notes:v.notes,p_employee_id:null});if(!r.ok){out.textContent=r.error||'No se pudo guardar';out.className='msg error';return false}out.textContent='Guardado y sincronizado';out.className='msg ok';return true}
async function clearDate(date,root){if(!confirm('¿Borrar las horas de este día?'))return;const r=await api('clear',{p_session_token:token,p_work_date:date,p_employee_id:null});const out=root.querySelector('[data-field=msg]');if(!r.ok){out.textContent=r.error||'No se pudo borrar';out.className='msg error';return}out.textContent='Día borrado';out.className='msg ok';setTimeout(()=>renderTab(activeTab),250)}
function bindEditor(root,date,e){bindSteppers(root);root.querySelector('[data-field=incident]').value=e.incident||'';root.querySelector('[data-action=save]').onclick=async()=>{if(await saveDate(date,root)){setTimeout(()=>renderTab(activeTab),350)}};root.querySelector('[data-action=clear]').onclick=()=>clearDate(date,root)}
async function renderToday(){const d=dayCursor,s=iso(d),arr=await entries(s,s),e=arr[0]||{};q('tabToday').innerHTML=`<div class="card"><div class="dayNav"><button id="prevDay" class="navArrow">‹</button><div class="dayTitle"><strong>${d.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</strong><span>Periodo nómina 21 → 20</span></div><button id="nextDay" class="navArrow">›</button></div><button id="backToday" class="backToday">VOLVER A HOY</button></div><div class="workType">${workLabel(d)}</div><div class="sectionTitle">Horas del día</div><div id="todayEditor">${editorFields(e)}</div>`;bindEditor(q('todayEditor'),s,e);q('prevDay').onclick=()=>{dayCursor=new Date(d.getFullYear(),d.getMonth(),d.getDate()-1);renderToday()};q('nextDay').onclick=()=>{dayCursor=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1);renderToday()};q('backToday').onclick=()=>{dayCursor=new Date();renderToday()}}
async function renderMonth(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth(),[ma,mb]=monthBounds(y,m),[pa,pb]=payrollBounds(y,m);const [monthEntries,payEntries]=await Promise.all([entries(iso(ma),iso(mb)),entries(iso(pa),iso(pb))]),S=sums(payEntries),map=Object.fromEntries(monthEntries.map(e=>[e.date,e]));let rows='';for(let d=1;d<=mb.getDate();d++){const dt=new Date(y,m,d),s=iso(dt),e=map[s];let chips='';if(e){if(num(e.normal))chips+=`<span class="chip">N ${fmt(e.normal)}</span>`;if(num(e.extra))chips+=`<span class="chip g">E ${fmt(e.extra)}</span>`;if(num(e.holiday))chips+=`<span class="chip b">F ${fmt(e.holiday)}</span>`;if(num(e.personal))chips+=`<span class="chip y">P ${fmt(e.personal)}</span>`;if(e.incident==='vacation')chips+=`<span class="chip g">VC</span>`}rows+=`<div class="dayRow" data-date="${s}"><div class="dayBubble"><div><span>${d}</span><small>${dt.toLocaleDateString('es-ES',{weekday:'short'}).replace('.','')}</small></div></div><div class="dayMain"><b>${e?(e.worksite||displayIncident(e.incident)):'Sin registro'}</b><div>${e?(e.notes||displayIncident(e.incident)):'Pulsa para rellenar'}</div></div><div class="chips">${chips||'<span class="chip">—</span>'}</div></div>`}q('tabMonth').innerHTML=`<div class="card"><div class="monthNav"><button id="prevMonth">‹</button><div class="monthName">${monthCursor.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</div><button id="nextMonth">›</button></div><div class="period">Nómina ${iso(pa).split('-').reverse().join('/')} → ${iso(pb).split('-').reverse().join('/')}</div><div class="summaryCards"><div class="sumCard"><span>NORMALES</span><b>${fmt(S.n)} h</b></div><div class="sumCard"><span>EXTRA</span><b>${fmt(S.e)} h</b></div><div class="sumCard"><span>FESTIVAS</span><b>${fmt(S.h)} h</b></div></div><div style="margin-top:18px">${rows}</div></div>`;q('prevMonth').onclick=()=>{monthCursor=new Date(y,m-1,1);renderMonth()};q('nextMonth').onclick=()=>{monthCursor=new Date(y,m+1,1);renderMonth()};q('tabMonth').querySelectorAll('[data-date]').forEach(x=>x.onclick=()=>openEdit(x.dataset.date))}
async function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),[a,b]=monthBounds(y,m),arr=await entries(iso(a),iso(b)),map=Object.fromEntries(arr.map(e=>[e.date,e]));let cells='';const off=(a.getDay()+6)%7;for(let i=0;i<off;i++)cells+='<div class="calday blank"></div>';for(let d=1;d<=b.getDate();d++){const dt=new Date(y,m,d),s=iso(dt),e=map[s],today=s===iso(new Date());cells+=`<button class="calday ${e?'has':''} ${today?'today':''}" data-date="${s}">${d}</button>`}q('tabCalendar').innerHTML=`<div class="card"><div class="monthNav"><button id="prevCal">‹</button><div class="monthName">${calCursor.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</div><button id="nextCal">›</button></div><div class="calendarWeek" style="margin-top:18px"><div class="dow">L</div><div class="dow">M</div><div class="dow">X</div><div class="dow">J</div><div class="dow">V</div><div class="dow">S</div><div class="dow">D</div>${cells}</div></div>`;q('prevCal').onclick=()=>{calCursor=new Date(y,m-1,1);renderCalendar()};q('nextCal').onclick=()=>{calCursor=new Date(y,m+1,1);renderCalendar()};q('tabCalendar').querySelectorAll('[data-date]').forEach(x=>x.onclick=()=>openEdit(x.dataset.date))}
async function renderSummary(){const y=new Date().getFullYear(),rangeStart=(y-1)+'-12-21',rangeEnd=y+'-12-20';const [annual,payrollYear]=await Promise.all([entries(y+'-01-01',y+'-12-31'),entries(rangeStart,rangeEnd)]),A=sums(annual),vac=num(me.annual_vacation_days||30),pers=num(me.annual_personal_hours||12);let rows='';for(let m=0;m<12;m++){const [a,b]=payrollBounds(y,m),arr=payrollYear.filter(e=>e.date>=iso(a)&&e.date<=iso(b)),S=sums(arr),label=new Date(y,m,1).toLocaleDateString('es-ES',{month:'long'});rows+=`<div class="summaryLine"><span style="text-transform:capitalize">${label}<small style="display:block;color:#909892">${pad(a.getDate())}/${pad(a.getMonth()+1)}→${pad(b.getDate())}/${pad(b.getMonth()+1)}</small></span><span>${fmt(S.n)}</span><b>${fmt(S.e)}</b><span>${fmt(S.h)}</span></div>`}q('tabSummary').innerHTML=`<div class="card"><div class="sectionTitle" style="margin-bottom:8px">Resumen ${y}</div><div class="summaryCards"><div class="sumCard"><span>VACACIONES</span><b>${A.v} / ${fmt(vac)}</b></div><div class="sumCard"><span>PERSONALES</span><b>${fmt(A.p)} / ${fmt(pers)} h</b></div><div class="sumCard"><span>EXTRA ANUAL</span><b>${fmt(A.e)} h</b></div></div><div class="summaryHead" style="margin-top:20px"><span>PERIODO</span><span>NORMAL</span><span>EXTRA</span><span>FEST.</span></div>${rows}</div>`}
async function renderProfile(){q('tabProfile').innerHTML=`<div class="card"><div class="sectionTitle">Mi perfil</div><div class="profileLine"><span>Nombre</span><b>${esc(me.full_name)}</b></div><div class="profileLine"><span>Rol</span><b>${me.role==='admin'?'Administrador':'Trabajador'}</b></div><div class="profileLine"><span>Vacaciones anuales</span><b>${fmt(me.annual_vacation_days||30)} días</b></div><div class="profileLine"><span>Horas personales</span><b>${fmt(me.annual_personal_hours||12)} h</b></div><button id="logoutBtn" class="dangerBtn" style="width:100%;margin-top:22px">CERRAR SESIÓN</button></div>`;q('logoutBtn').onclick=logout}
async function renderCompany(){const now=new Date(),m=now.getDate()>=21?now.getMonth()+1:now.getMonth(),y=now.getDate()>=21?(m===12?now.getFullYear()+1:now.getFullYear()):now.getFullYear(),mm=m===12?0:m,[a,b]=payrollBounds(y,mm),r=await api('admin/summary',{p_session_token:token,p_start_date:iso(a),p_end_date:iso(b)});if(!r.ok)throw new Error(r.error||'No se pudo cargar empresa');let rows=(r.employees||[]).map(e=>`<div class="employeeLine"><div class="employeeName">${esc(e.full_name)}</div><div class="employeeStats">Normales <b>${fmt(e.normal)}</b> · Extra <b>${fmt(e.extra)}</b> · Festivas <b>${fmt(e.holiday)}</b> · VC <b>${e.vacations}</b></div></div>`).join('');q('tabCompany').innerHTML=`<div class="card"><div class="sectionTitle" style="margin-bottom:8px">Empresa</div><div class="period">Periodo ${iso(a).split('-').reverse().join('/')} → ${iso(b).split('-').reverse().join('/')}</div>${rows||'<div class="empty">Sin datos</div>'}</div>`}
async function openEdit(date){selectedDate=date;const arr=await entries(date,date),e=arr[0]||{};q('editTitle').textContent=new Date(date+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});q('editBody').innerHTML=`<div class="workType" style="margin-top:20px">${workLabel(new Date(date+'T12:00:00'))}</div><div id="modalEditor">${editorFields(e)}</div>`;bindEditor(q('modalEditor'),date,e);q('editModal').classList.remove('hidden')}
q('closeEdit').onclick=()=>q('editModal').classList.add('hidden');q('editModal').onclick=e=>{if(e.target===q('editModal'))q('editModal').classList.add('hidden')}
async function renderTab(tab){activeTab=tab;['Today','Month','Calendar','Summary','Profile','Company'].forEach(t=>q('tab'+t).classList.toggle('hidden',t!==tab));qa('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));try{if(tab==='Today')await renderToday();if(tab==='Month')await renderMonth();if(tab==='Calendar')await renderCalendar();if(tab==='Summary')await renderSummary();if(tab==='Profile')await renderProfile();if(tab==='Company')await renderCompany()}catch(e){q('tab'+tab).innerHTML=`<div class="card"><div class="msg error">${esc(e.message)}</div></div>`}}
qa('.navBtn').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));
function showApp(){q('login').classList.add('hidden');q('changePin').classList.add('hidden');q('main').classList.remove('hidden');q('bottomNav').classList.remove('hidden');q('who').textContent=me.full_name||'';q('companyBtn').classList.toggle('hidden',me.role!=='admin');renderTab('Today')}
async function boot(){if(!token)return;const r=await api('me',{p_session_token:token});if(!r.ok){localStorage.removeItem('efs_token');token='';return}me=r;showApp()}
q('loginBtn').onclick=async()=>{showMsg('loginMsg','');const u=q('username').value.trim(),p=q('pin').value.trim();if(!u||!/^[0-9]{6}$/.test(p)){showMsg('loginMsg','Introduce usuario y PIN de 6 cifras');return}const r=await api('login',{p_username:u,p_pin:p});if(!r.ok){showMsg('loginMsg',r.error||'No se pudo iniciar sesión');return}token=r.session_token;localStorage.setItem('efs_token',token);if(r.must_change_pin){q('login').classList.add('hidden');q('changePin').classList.remove('hidden');q('oldPin').value=p;return}const mr=await api('me',{p_session_token:token});if(!mr.ok){showMsg('loginMsg',mr.error||'No se pudo cargar el perfil');return}me=mr;showApp()}
q('changeBtn').onclick=async()=>{const o=q('oldPin').value.trim(),n=q('newPin').value.trim();if(!/^[0-9]{6}$/.test(n)){showMsg('pinMsg','El PIN nuevo debe tener 6 cifras');return}const r=await api('change-pin',{p_session_token:token,p_current_pin:o,p_new_pin:n});if(!r.ok){showMsg('pinMsg',r.error||'No se pudo cambiar');return}me=await api('me',{p_session_token:token});showApp()}
async function logout(){try{await api('logout',{p_session_token:token})}catch{}localStorage.removeItem('efs_token');location.reload()}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
boot();
})();