(function(){
'use strict';
const API='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-fichajes/api/';
const V3='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-admin-v3';
const GS='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-gestor-sync';
const REG='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-registro-app';
const PAY='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-payroll-documents';
let token=localStorage.getItem('efs_admin_web_token_v3')||'',me=null,employees=[],caeData=null,caeScope='employee',caeFilter='all',mineTab='day',historyMonths=[],historyYear=new Date().getFullYear(),sigMode=null,sigPayload=null,sigDirty=false;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const dmy=s=>{const a=String(s||'').slice(0,10).split('-');return a.length===3?a[2]+'/'+a[1]+'/'+a[0]:'—'};
const fmt=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):String(Math.round(n*100)/100).replace('.',',')};
const madridToday=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const monthName=(m,y)=>['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][Number(m)-1]+' '+y;
const officialMonth=s=>{try{return new Date(s+'-01T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'}).replace(/^./,x=>x.toUpperCase())}catch{return s}};
async function post(base,path,body){try{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{}),cache:'no-store'});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={ok:false,error:t||'Respuesta no válida'}}if(!r.ok&&j.ok!==false)j.ok=false;return j}catch(e){return{ok:false,error:'Sin conexión'}}}
const api=(p,b)=>post(API,p,b);
const v3=(p,b)=>post(V3,p,Object.assign({p_session_token:token},b||{}));
const gs=(p,b)=>post(GS,p,Object.assign({p_session_token:token},b||{}));
const reg=(p,b)=>post(REG,p,Object.assign({p_session_token:token},b||{}));
const pay=(p,b)=>post(PAY,p,Object.assign({session_token:token},b||{}));
function closeMenu(){$('#sidebar').classList.remove('open');$('#shade').classList.remove('open')}
function setLoginMsg(t){$('#loginMsg').textContent=t||''}
async function login(){const u=$('#username').value.trim(),p=$('#pin').value.trim();if(!u||p.length!==6)return setLoginMsg('Introduce usuario y PIN de 6 cifras');const b=$('#loginBtn');b.disabled=true;b.textContent='ENTRANDO…';setLoginMsg('');const r=await api('login',{p_username:u,p_pin:p});if(!r.ok){b.disabled=false;b.textContent='ENTRAR';return setLoginMsg(r.error||'No se pudo iniciar sesión')}token=r.session_token||'';const m=await api('me',{p_session_token:token});if(!m.ok||m.role!=='admin'){b.disabled=false;b.textContent='ENTRAR';token='';return setLoginMsg('Esta web es solo para administradores')}me=m;localStorage.setItem('efs_admin_web_token_v3',token);openApp()}
async function boot(){if(!token)return;const m=await api('me',{p_session_token:token});if(m.ok&&m.role==='admin'){me=m;openApp()}else{token='';localStorage.removeItem('efs_admin_web_token_v3')}}
function openApp(){$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');$('#sideWho').textContent=(me.full_name||'Administrador')+' · Admin';render('dashboard')}
function logout(){localStorage.removeItem('efs_admin_web_token_v3');location.reload()}
const titles={dashboard:['Inicio','Resumen general'],mine:['Mi zona','Jornada, registros y nóminas personales'],workers:['Trabajadores','Plantilla activa'],punches:['Fichajes empresa','Estado de la jornada de hoy'],hours:['Registro de horas','Horas e incidencias'],payroll:['Nóminas empresa','Gestión de nóminas y firmas'],cae:['CAE / PRL','Solo lectura'],company:['Empresa','Documentación de empresa'],accounting:['Contabilidad','Facturas, pedidos y banco'],rates:['Precio hora obra','Cálculo de costes']};
function setNav(p){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#topTitle').textContent=titles[p]?.[0]||p;$('#topSub').textContent=titles[p]?.[1]||'';closeMenu()}
async function render(p){setNav(p);$('#content').innerHTML='<div class="card">Cargando…</div>';try{if(p==='dashboard')return await renderDashboard();if(p==='mine')return await renderMine();if(p==='workers')return await renderWorkers();if(p==='punches')return await renderPunches();if(p==='cae')return await renderCAE();return renderStub(p)}catch(e){$('#content').innerHTML='<div class="card"><b>No se pudo cargar</b><div class="muted" style="margin-top:7px">'+esc(e?.message||e)+'</div></div>'}}
async function loadEmployees(){if(employees.length)return employees;let r=await api('admin/employees',{p_session_token:token});if(r.ok)employees=r.employees||r.items||[];if(!employees.length){const d=new Date(),a=new Date(d.getFullYear(),d.getMonth(),1),b=new Date(d.getFullYear(),d.getMonth()+1,0);r=await api('admin/summary',{p_session_token:token,p_start_date:iso(a),p_end_date:iso(b)});if(r.ok)employees=r.employees||[]}return employees}
async function renderDashboard(){const list=await loadEmployees();let stats={clocked:'—',missing:'—',inc:'—'};const z=await gs('/admin/today');if(z.ok){const by=new Map((z.entries||[]).map(e=>[String(e.employee_id),e])),people=(z.profiles||[]).filter(x=>x.active!==false);stats.clocked=people.filter(x=>by.get(String(x.id))?.started_at).length;stats.inc=people.filter(x=>!by.get(String(x.id))?.started_at&&!!by.get(String(x.id))?.incident).length;stats.missing=people.filter(x=>!by.get(String(x.id))?.started_at&&!by.get(String(x.id))?.incident).length}const cards=[['mine','●','Mi zona','Tu fichaje, registros oficiales y nóminas'],['workers','👷','Trabajadores','Plantilla y ficha de cada trabajador'],['punches','✓','Fichajes empresa','Quién ha fichado hoy'],['hours','◷','Registro de horas','Horas e incidencias sin tablas gigantes'],['payroll','€','Nóminas empresa','Control de publicación y firmas'],['cae','📁','CAE / PRL','Consulta documental en solo lectura'],['company','🏢','Empresa','Documentación de empresa'],['accounting','▤','Contabilidad','Facturas, pedidos y banco'],['rates','€/h','Precio hora obra','Costes y precio recomendado']];$('#content').innerHTML=`<div class="hero"><div><h1>Panel de administración</h1><p>Misma línea visual que Windows, pero repartida en menús más pequeños.</p></div><span class="pill">WEB · PRUEBA V3</span></div><div class="grid"><div class="card kpi"><span>Trabajadores</span><b>${list.filter(x=>x.active!==false).length||'—'}</b></div><div class="card kpi"><span>Fichados hoy</span><b>${stats.clocked}</b></div><div class="card kpi"><span>Sin fichar</span><b>${stats.missing}</b></div><div class="card kpi"><span>Incidencias</span><b>${stats.inc}</b></div></div><div class="menuGrid">${cards.map(x=>`<button class="menuCard" data-go="${x[0]}"><span class="mi">${x[1]}</span><div><strong>${x[2]}</strong><small>${x[3]}</small></div></button>`).join('')}</div>`;$$('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go))}
async function renderMine(){mineTab=mineTab||'day';$('#content').innerHTML=`<div class="hero"><div><h1>Mi zona</h1><p>Área personal de ${esc((me.full_name||'Administrador').split(' ').slice(0,2).join(' '))}.</p></div><span class="pill">PERSONAL</span></div><div class="mineGrid"><button class="mineTab" data-mine="day">✓<b>MI JORNADA</b><small>Fichar hoy y ver tu estado</small></button><button class="mineTab" data-mine="history">▦<b>MIS REGISTROS</b><small>Histórico oficial y firma mensual</small></button><button class="mineTab" data-mine="payroll">€<b>MIS NÓMINAS</b><small>Ver, descargar y firmar recepción</small></button></div><div id="mineBody"></div>`;$$('[data-mine]').forEach(b=>b.onclick=()=>setMineTab(b.dataset.mine));await setMineTab(mineTab)}
async function setMineTab(t){mineTab=t;$$('[data-mine]').forEach(b=>b.classList.toggle('active',b.dataset.mine===t));$('#mineBody').innerHTML='<div class="card">Cargando…</div>';if(t==='day')return renderMyDay();if(t==='history')return renderHistory();return renderMyPayroll()}
function ownStatus(entry){if(!entry)return{kind:'missing',label:'Sin fichar'};if(entry.started_at)return{kind:'clocked',label:'Fichado',time:new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(new Date(entry.started_at))};if(String(entry.source||'').toLowerCase()==='admin_regularization')return{kind:'blocked',label:'Regularizado'};if(entry.incident)return{kind:'blocked',label:'Incidencia: '+entry.incident};return{kind:'missing',label:'Sin fichar'}}
async function renderMyDay(){const z=await gs('/admin/today');if(!z.ok){$('#mineBody').innerHTML='<div class="card bad">'+esc(z.error||'No se pudo cargar tu fichaje')+'</div>';return}const profiles=(z.profiles||[]).filter(p=>p.active!==false),by=new Map((z.entries||[]).map(e=>[String(e.employee_id),e])),currentId=String(z.current_admin_id||me.id||''),person=profiles.find(p=>p.role==='admin'&&String(p.id)===currentId)||profiles.find(p=>p.role==='admin'&&String(p.full_name||'').toLowerCase()===String(me.full_name||'').toLowerCase());if(!person){$('#mineBody').innerHTML='<div class="card bad">No se ha podido relacionar tu usuario con el perfil de fichaje.</div>';return}const st=ownStatus(by.get(String(person.id))),date=new Date(String(z.work_date)+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});$('#mineBody').innerHTML=`<div class="card ownPunch"><div class="ownName">${esc(person.full_name)}</div><div class="ownDate">${esc(date)} · Jornada ordinaria 8 h</div>${st.kind==='clocked'?`<div class="ownStatus"><div><div class="muted">JORNADA INICIADA</div><div class="ownTime">${esc(st.time)}</div></div><span class="state ok">FICHADO</span></div>`:st.kind==='blocked'?`<div class="ownStatus"><strong>${esc(st.label)}</strong><span class="state warn">BLOQUEADO</span></div>`:`<div class="ownStatus"><strong>Sin fichar</strong><span class="state warn">PENDIENTE</span></div><button id="punchMe" class="punchBtn">INICIAR JORNADA · 8 H</button><div class="muted" style="font-size:10px;text-align:center;margin-top:8px">Se guardará la hora real exacta al pulsar.</div>`}</div>`;if($('#punchMe'))$('#punchMe').onclick=async()=>{if(!confirm('¿Iniciar ahora tu jornada?\n\nSe guardará la hora real y 8 horas ordinarias.'))return;const b=$('#punchMe');b.disabled=true;b.textContent='FICHANDO…';const r=await gs('/admin/start-admin-day',{employee_id:person.id});if(!r.ok){b.disabled=false;b.textContent='INICIAR JORNADA · 8 H';return alert(r.error||'No se pudo fichar')}renderMyDay()}}
async function renderHistory(){const z=await reg('/months');if(!z.ok){$('#mineBody').innerHTML='<div class="card bad">'+esc(z.error||'No se pudo cargar el histórico')+'</div>';return}historyMonths=(z.months||[]).filter(m=>String(m.month||'')>='2025-01');const years=[...new Set(historyMonths.map(m=>Number(String(m.month).slice(0,4))).filter(Boolean))].sort((a,b)=>b-a);if(!years.includes(historyYear))historyYear=years[0]||new Date().getFullYear();const items=historyMonths.filter(m=>Number(String(m.month).slice(0,4))===historyYear);$('#mineBody').innerHTML=`<div class="sectionHead"><div><h2>Mis registros oficiales</h2><div class="muted">Histórico de jornada y firma mensual.</div></div><div class="toolbar">${years.map(y=>`<button class="btn ${y===historyYear?'primary':''}" data-year="${y}">${y}</button>`).join('')}</div></div><div class="monthList">${items.map((m,i)=>{const signed=!!m.signed,can=!signed&&!!m.can_confirm&&!m.needs_review;return`<div class="monthCard ${signed?'signed':''}"><div class="monthTop"><div><div class="monthName">${esc(officialMonth(m.month))}</div><div class="meta">${Number(m.record_count||0)} registros · ${fmt(Number(m.effective_minutes||0)/60)} h efectivas</div></div><span class="state ${signed?'ok':m.needs_review?'bad':'warn'}">${signed?'FIRMADO ✓':m.needs_review?'REVISIÓN':can?'PENDIENTE FIRMA':'EN CURSO'}</span></div><div class="actions" style="margin-top:10px"><button class="btn" data-view-month="${i}">Ver mes</button>${can?`<button class="btn primary" data-sign-month="${i}">Firmar mes</button>`:''}</div></div>`}).join('')||'<div class="card empty">No hay meses oficiales en este año.</div>'}</div>`;$$('[data-year]').forEach(b=>b.onclick=()=>{historyYear=Number(b.dataset.year);renderHistory()});$$('[data-view-month]').forEach(b=>b.onclick=()=>openOfficialMonth(items[Number(b.dataset.viewMonth)]));$$('[data-sign-month]').forEach(b=>b.onclick=()=>openSignature('official',{month:items[Number(b.dataset.signMonth)]}))}
async function openOfficialMonth(m){$('#mineBody').innerHTML='<div class="card">Cargando mes…</div>';const z=await reg('/records',{p_start_date:m.period_start,p_end_date:m.period_end});if(!z.ok){$('#mineBody').innerHTML='<button class="btn backBtn" id="backHist">← Histórico</button><div class="card bad">'+esc(z.error||'No se pudo cargar')+'</div>';$('#backHist').onclick=renderHistory;return}const kind=k=>({workday:'Laborable',vacation:'Vacaciones',sick_leave:'Baja / IT',holiday:'Festivo',absence:'Falta',weekend:'Fin de semana'})[k]||k||'';const times=e=>{const p=[];if(e.morning_start||e.morning_end)p.push((e.morning_start||'—')+'–'+(e.morning_end||'—'));if(e.afternoon_start||e.afternoon_end)p.push((e.afternoon_start||'—')+'–'+(e.afternoon_end||'—'));return p.join(' · ')||'—'};$('#mineBody').innerHTML=`<button class="btn backBtn" id="backHist">← Histórico</button><div class="card"><div class="sectionHead"><div><h2>${esc(officialMonth(m.month))}</h2><div class="muted">${dmy(m.period_start)} → ${dmy(m.period_end)}</div></div></div><div class="recordList">${(z.entries||[]).map(e=>`<div class="record"><div><b>${dmy(e.date).slice(0,5)}</b></div><div><b>${esc(kind(e.day_kind))}</b><div class="meta">${esc(times(e))}</div></div><div class="recordHours">${fmt(Number(e.effective_minutes||0)/60)} h</div></div>`).join('')}</div></div>`;$('#backHist').onclick=renderHistory}
async function renderMyPayroll(){const z=await pay('/worker/list');if(!z.ok){$('#mineBody').innerHTML='<div class="card bad">'+esc(z.error||'No se pudieron cargar tus nóminas')+'</div>';return}const items=z.items||[];$('#mineBody').innerHTML=`<div class="sectionHead"><div><h2>Mis nóminas</h2><div class="muted">Consulta y firma de recepción.</div></div></div><div class="payList">${items.map((x,i)=>{const signed=!!x.receipt?.signed_at,can=!signed&&(!x.available_date||madridToday()>=String(x.available_date).slice(0,10));return`<div class="payCard ${signed?'signed':''}"><div class="payTop"><div><div class="payName">${esc(monthName(x.payroll_month,x.payroll_year))}</div><div class="meta">Puesta a disposición: ${dmy(x.available_date)}</div></div><span class="state ${signed?'ok':'warn'}">${signed?'FIRMADA ✓':can?'PENDIENTE FIRMA':'AÚN NO DISPONIBLE'}</span></div><div class="actions" style="margin-top:10px"><button class="btn" data-pay="view" data-i="${i}">Ver</button><button class="btn" data-pay="download" data-i="${i}">Descargar</button>${signed?`<button class="btn" data-pay="certificate" data-i="${i}">Certificado</button>`:can?`<button class="btn primary" data-pay="sign" data-i="${i}">Firmar recepción</button>`:''}</div></div>`}).join('')||'<div class="card empty">Todavía no tienes nóminas publicadas.</div>'}</div>`;$$('[data-pay]').forEach(b=>b.onclick=()=>{const x=items[Number(b.dataset.i)],mode=b.dataset.pay;if(mode==='sign')openSignature('payroll',{doc:x});else openPayroll(x,mode)})}
async function openPayroll(doc,mode){let z;if(mode==='certificate')z=await pay('/worker/certificate-url',{document_id:doc.id,download:false});else z=await pay('/worker/url',{document_id:doc.id,download:mode==='download'});if(!z.ok)return alert(z.error||'No se pudo abrir');window.open(z.url,'_blank','noopener')}
async function renderWorkers(){const list=(await loadEmployees()).filter(x=>x.active!==false);$('#content').innerHTML=`<div class="sectionHead"><div><h2>Trabajadores</h2><div class="muted">Lista compacta. Cada ficha irá en su propia pantalla.</div></div><input id="workerSearch" class="search" placeholder="Buscar trabajador…"></div><div id="workerList" class="list"></div>`;const draw=()=>{const q=$('#workerSearch').value.trim().toLowerCase(),a=list.filter(x=>String(x.full_name||x.name||'').toLowerCase().includes(q));$('#workerList').innerHTML=a.map(x=>`<div class="row"><div><b>${esc(x.full_name||x.name||'Trabajador')}</b><small>${esc(x.dni_nie||x.dni||'')}</small></div><span class="state ok">ACTIVO</span></div>`).join('')||'<div class="empty">Sin resultados</div>'};$('#workerSearch').oninput=draw;draw()}
async function renderPunches(){const z=await gs('/admin/today');if(!z.ok)throw Error(z.error||'No se pudieron cargar los fichajes');const by=new Map((z.entries||[]).map(e=>[String(e.employee_id),e])),people=(z.profiles||[]).filter(x=>x.active!==false).sort((a,b)=>String(a.full_name).localeCompare(String(b.full_name),'es'));$('#content').innerHTML=`<div class="sectionHead"><div><h2>Fichajes de hoy</h2><div class="muted">Equipo completo. Tu fichaje personal está en Mi zona.</div></div><button id="refreshPunch" class="btn">Actualizar</button></div><div class="list">${people.map(p=>{const e=by.get(String(p.id));let cl='warn',txt='Sin fichar',det='';if(e?.started_at){cl='ok';txt='Fichado';det=new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(new Date(e.started_at))}else if(e?.incident){cl='info';txt='Incidencia';det=e.incident}return`<div class="row"><div><b>${esc(p.full_name)}</b><small>${p.role==='admin'?'Administrador':'Trabajador'}${det?' · '+esc(det):''}</small></div><span class="state ${cl}">${txt}</span></div>`}).join('')}</div>`;$('#refreshPunch').onclick=renderPunches}
function docState(x){const s=String(x.status||'');if(s==='expired')return['bad','Caducado'];if(s==='upcoming')return['warn','Próximo'];if(s==='pending')return['warn','Pendiente'];if(s==='not_required')return['info','No requerido'];return['ok','Vigente']}
async function renderCAE(){if(!caeData){const z=await v3('/docs/list');if(!z.ok)throw Error(z.error||'No se pudo cargar CAE');caeData=z}drawCAE()}
function drawCAE(){const all=(caeData.items||[]).filter(x=>!String(x.document_code||'').startsWith('sys_')),scoped=all.filter(x=>x.scope===caeScope),f=scoped.filter(x=>caeFilter==='all'||x.status===caeFilter);$('#content').innerHTML=`<div class="hero"><div><h1>CAE / PRL</h1><p>Consulta documental. Sin edición desde esta web.</p></div><span class="pill">🔒 SOLO LECTURA</span></div><div class="notice">Aquí no se puede añadir, sustituir, editar, borrar ni cambiar requisitos.</div><div class="toolbar"><button class="btn ${caeScope==='employee'?'primary':''}" data-scope="employee">Empleados</button><button class="btn ${caeScope==='company'?'primary':''}" data-scope="company">Empresa</button><button id="caeRefresh" class="btn">Actualizar</button></div><div class="toolbar"><button class="btn ${caeFilter==='all'?'primary':''}" data-filter="all">Todos</button><button class="btn ${caeFilter==='pending'?'primary':''}" data-filter="pending">Pendientes</button><button class="btn ${caeFilter==='expired'?'primary':''}" data-filter="expired">Caducados</button><button class="btn ${caeFilter==='upcoming'?'primary':''}" data-filter="upcoming">Próximos</button></div><div class="docGrid">${f.map(x=>{const [cl,st]=docState(x);return`<div class="card"><div class="docName">${esc(x.document_name||x.type_name||x.original_name||'Documento')}</div><div class="docMeta"><span>${esc(x.owner_name||'')}</span><span>${esc(x.category||'')}</span><span>${x.expiry_date?'Caduca: '+dmy(x.expiry_date):'Sin caducidad indicada'}</span></div><span class="state ${cl}" style="display:inline-block;margin-top:9px">${st}</span><div class="docActions">${x.file_id?`<button class="btn" data-open="${x.file_id}">Abrir</button><button class="btn" data-down="${x.file_id}">Descargar</button>`:'<span class="muted">Sin archivo adjunto</span>'}</div></div>`}).join('')||'<div class="card empty">No hay documentos en este filtro.</div>'}</div>`;$$('[data-scope]').forEach(b=>b.onclick=()=>{caeScope=b.dataset.scope;drawCAE()});$$('[data-filter]').forEach(b=>b.onclick=()=>{caeFilter=b.dataset.filter;drawCAE()});$$('[data-open]').forEach(b=>b.onclick=()=>openDoc(b.dataset.open,false));$$('[data-down]').forEach(b=>b.onclick=()=>openDoc(b.dataset.down,true));$('#caeRefresh').onclick=async()=>{caeData=null;await renderCAE()}}
async function openDoc(id,download){const z=await v3('/docs/url',{file_id:id,download});if(!z.ok)return alert(z.error||'No se pudo abrir');window.open(z.url,'_blank','noopener')}
function renderStub(p){const labels={hours:['Registro de horas','Aquí separaré resumen mensual, edición de un día e incidencias.'],payroll:['Nóminas empresa','Gestión de todas las nóminas y firmas de la empresa. Tus nóminas personales ya están en Mi zona.'],company:['Empresa','Documentación de empresa en una pantalla independiente.'],accounting:['Contabilidad','Facturas, pedidos, banco, conciliación y resumen en menús separados.'],rates:['Precio hora obra','Cálculo de costes separado del resultado y del histórico.']},x=labels[p];$('#content').innerHTML=`<div class="hero"><div><h1>${x[0]}</h1><p>${x[1]}</p></div><span class="pill">SIGUIENTE FASE</span></div><div class="card">Este apartado ya tiene su hueco propio para no acumular demasiada información en una sola pantalla.</div>`}
function openSignature(mode,payload){sigMode=mode;sigPayload=payload;sigDirty=false;$('#sigTitle').textContent=mode==='official'?'Firma del registro':'Firma de recepción';$('#sigSub').textContent=mode==='official'?officialMonth(payload.month.month):monthName(payload.doc.payroll_month,payload.doc.payroll_year);$('#sigMsg').textContent='Firma dentro del recuadro con el dedo.';$('#sigSave').disabled=false;$('#sigSave').textContent='Firmar';$('#sigOverlay').classList.remove('hidden');setTimeout(initCanvas,40)}
function closeSignature(){$('#sigOverlay').classList.add('hidden');sigMode=null;sigPayload=null;sigDirty=false}
function initCanvas(){const c=$('#sigCanvas'),r=c.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1)),w=Math.max(280,r.width||320),h=210;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#111';ctx.lineWidth=2.5;ctx.lineCap='round';ctx.lineJoin='round';sigDirty=false;let down=false;const pos=e=>{const rr=c.getBoundingClientRect();return{x:e.clientX-rr.left,y:e.clientY-rr.top}};c.onpointerdown=e=>{e.preventDefault();down=true;try{c.setPointerCapture(e.pointerId)}catch{}const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+.1,p.y+.1);ctx.stroke();sigDirty=true};c.onpointermove=e=>{if(!down)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};c.onpointerup=c.onpointercancel=e=>{if(down){e.preventDefault();down=false}}}
async function saveSignature(){if(!sigDirty)return $('#sigMsg').textContent='Primero dibuja tu firma.';const mode=sigMode,payload=sigPayload,c=$('#sigCanvas'),b=$('#sigSave'),data=c.toDataURL('image/png');b.disabled=true;b.textContent='Guardando…';$('#sigMsg').textContent='Guardando firma…';let z;if(mode==='official')z=await reg('/confirm',{p_start_date:payload.month.period_start,p_end_date:payload.month.period_end,p_signature_base64:data.split(',')[1]});else z=await pay('/worker/sign',{document_id:payload.doc.id,signature_data_url:data});if(!z?.ok){b.disabled=false;b.textContent='Firmar';$('#sigMsg').textContent=z?.error||'No se pudo guardar la firma';return}$('#sigMsg').textContent='✓ Firma guardada correctamente';setTimeout(async()=>{closeSignature();if(mode==='official'){mineTab='history';await renderHistory()}else{mineTab='payroll';await renderMyPayroll()}},350)}
$('#loginBtn').onclick=login;$('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logout').onclick=logout;$$('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));$('#hamb').onclick=()=>{$('#sidebar').classList.add('open');$('#shade').classList.add('open')};$('#shade').onclick=closeMenu;$('#sigCancel').onclick=closeSignature;$('#sigClear').onclick=initCanvas;$('#sigSave').onclick=saveSignature;boot();
})();