(function(){
'use strict';
if(window.__efAdminFeaturesV7)return;window.__efAdminFeaturesV7=true;
var BASE='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-admin-web-api';
var $=function(s){return document.querySelector(s)}, $$=function(s){return Array.from(document.querySelectorAll(s))};
var esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
var tok=function(){return localStorage.getItem('efs_admin_web_token_v3')||''};
var fmt=function(n){return new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(Number(n||0))};
var euro=function(n){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n||0))};
var dmy=function(s){var a=String(s||'').slice(0,10).split('-');return a.length===3?a[2]+'/'+a[1]+'/'+a[0]:'—'};
var today=function(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date())};
var monthNow=function(){return today().slice(0,7)};
var monthBounds=function(m){var a=m.split('-').map(Number),last=new Date(a[0],a[1],0).getDate();return {start:a[0]+'-'+String(a[1]).padStart(2,'0')+'-01',end:a[0]+'-'+String(a[1]).padStart(2,'0')+'-'+String(last).padStart(2,'0')}};
async function api(path,body){body=body||{};body.p_session_token=tok();try{var r=await fetch(BASE+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),t=await r.text(),z;try{z=JSON.parse(t)}catch(e){z={ok:false,error:t||'Respuesta no válida'}}if(!r.ok&&z.ok!==false)z.ok=false;return z}catch(e){return{ok:false,error:'Sin conexión'}}}
function head(a,b){if($('#topTitle'))$('#topTitle').textContent=a;if($('#topSub'))$('#topSub').textContent=b||''}
function loading(){if($('#content'))$('#content').innerHTML='<div class="card">Cargando…</div>'}
function fail(t){if($('#content'))$('#content').innerHTML='<div class="card bad"><b>No se pudo cargar</b><div style="margin-top:6px">'+esc(t||'Error')+'</div></div>'}
function pill(c,t){return '<span class="state '+c+'">'+esc(t)+'</span>'}

var modal=null;
function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='ef7Modal hidden';modal.innerHTML='<div class="ef7ModalBox"><div class="ef7ModalHead"><b id="ef7ModalTitle">Editar</b><button class="btn" id="ef7ModalClose">Cerrar</button></div><div id="ef7ModalBody"></div></div>';document.body.appendChild(modal);modal.querySelector('#ef7ModalClose').onclick=function(){modal.classList.add('hidden')};modal.onclick=function(e){if(e.target===modal)modal.classList.add('hidden')};return modal}
function showModal(t,h){var m=ensureModal();m.querySelector('#ef7ModalTitle').textContent=t;m.querySelector('#ef7ModalBody').innerHTML=h;m.classList.remove('hidden');return m}
function closeModal(){if(modal)modal.classList.add('hidden')}

function bindPage(p,fn){var b=document.querySelector('.nav [data-page="'+p+'"]');if(b)b.onclick=function(){document.querySelectorAll('.nav [data-page]').forEach(function(x){x.classList.toggle('active',x===b)});fn()}}
function captureCards(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-go]');if(!b)return;var p=b.dataset.go,map={workers:renderWorkers,punches:renderPunches,hours:renderHours,cae:renderCAE,company:renderCompany,rates:renderRates};if(map[p]){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();var n=document.querySelector('.nav [data-page="'+p+'"]');if(n)n.click();else map[p]()}},true)}

/* FICHAJES */
async function renderPunches(){
 head('Fichajes','Estado de hoy y regularizaciones');loading();
 var z=await api('/time/today');if(!z.ok)return fail(z.error);
 var by=new Map((z.entries||[]).map(function(x){return[String(x.employee_id),x]}));
 var people=(z.profiles||[]).filter(function(x){return x.active!==false}).sort(function(a,b){return String(a.full_name).localeCompare(String(b.full_name),'es')});
 var html='<div class="sectionHead"><div><h2>Fichajes · '+dmy(z.work_date)+'</h2><div class="muted">Regulariza olvidos sin entrar al gestor.</div></div><button class="btn primary" id="ef7RegOther">+ Regularizar otro día</button></div><div class="list">';
 people.forEach(function(p){var e=by.get(String(p.id)),st='Sin fichar',cl='warn',det='',can=true;if(e&&e.started_at){st='Fichado';cl='ok';det=new Date(e.started_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});can=false}else if(e&&e.incident){st='Incidencia';cl='info';det=e.incident;can=false}else if(e&&String(e.source||'')==='admin_regularization'){st='Regularizado';cl='ok';det=fmt(e.normal_hours)+' h';can=false}html+='<div class="row"><div><b>'+esc(p.full_name)+'</b><small>'+(p.role==='admin'?'Administrador':'Trabajador')+(det?' · '+esc(det):'')+'</small></div><div class="ef7RowActions">'+pill(cl,st)+(can?'<button class="btn" data-reg="'+p.id+'" data-name="'+esc(p.full_name)+'">Regularizar</button>':'')+'</div></div>'});
 html+='</div>';$('#content').innerHTML=html;
 $$('[data-reg]').forEach(function(b){b.onclick=function(){openReg(b.dataset.reg,b.dataset.name,z.work_date,[])}});
 $('#ef7RegOther').onclick=function(){openReg('','',z.work_date,people)};
}
function openReg(id,name,date,people){
 var opts='';if(people&&people.length){people.forEach(function(p){opts+='<option value="'+p.id+'" '+(String(p.id)===String(id)?'selected':'')+'>'+esc(p.full_name)+'</option>'})}else opts='<option value="'+id+'">'+esc(name)+'</option>';
 var m=showModal('Regularizar fichaje','<div class="ef7Form"><label>Trabajador<select id="erPerson">'+opts+'</select></label><label>Fecha<input id="erDate" type="date" value="'+esc(date||today())+'"></label><label>Horas ordinarias<input id="erHours" type="number" min=".5" max="24" step=".5" value="8"></label><label class="wide">Motivo<input id="erNote" value="Olvido de fichaje"></label><button class="btn primary wide" id="erSave">Guardar regularización</button><div id="erMsg" class="msg wide"></div></div>');
 m.querySelector('#erSave').onclick=async function(){var b=m.querySelector('#erSave');b.disabled=true;var r=await api('/time/regularize',{employee_id:m.querySelector('#erPerson').value,work_date:m.querySelector('#erDate').value,normal_hours:Number(m.querySelector('#erHours').value),notes:m.querySelector('#erNote').value});if(!r.ok){b.disabled=false;m.querySelector('#erMsg').textContent=r.error||'Error';return}closeModal();renderPunches()}
}

/* REGISTRO HORAS */
var hm=monthNow(),hd=null;
async function loadHours(){var b=monthBounds(hm),z=await api('/time/list',{start_date:b.start,end_date:b.end});if(!z.ok)throw Error(z.error||'No se pudo cargar');hd=z;return z}
async function renderHours(){
 head('Registro de horas','Horas e incidencias');loading();
 try{var z=await loadHours(),people=(z.profiles||[]).filter(function(x){return x.active!==false}),by=new Map();people.forEach(function(p){by.set(String(p.id),[])});(z.entries||[]).forEach(function(e){if(!by.has(String(e.employee_id)))by.set(String(e.employee_id),[]);by.get(String(e.employee_id)).push(e)});
 var h='<div class="sectionHead"><div><h2>Registro de horas</h2><div class="muted">Pulsa un trabajador para ver y editar sus días.</div></div><input id="ehMonth" class="search ef7Month" type="month" value="'+hm+'"></div><div class="ef7WorkerCards">';
 people.forEach(function(p){var a=by.get(String(p.id))||[],tot=a.reduce(function(s,e){return s+Number(e.normal_hours||0)+Number(e.overtime_hours||0)+Number(e.holiday_hours||0)+Number(e.personal_hours||0)},0);h+='<button class="ef7WorkerCard" data-hw="'+p.id+'"><div><b>'+esc(p.full_name)+'</b><small>'+a.length+' días registrados</small></div><strong>'+fmt(tot)+' h</strong></button>'});h+='</div>';$('#content').innerHTML=h;$('#ehMonth').onchange=function(e){hm=e.target.value||monthNow();renderHours()};$$('[data-hw]').forEach(function(b){b.onclick=function(){workerHours(b.dataset.hw)}})
 }catch(e){fail(e.message)}
}
function workerHours(id){
 var p=(hd.profiles||[]).find(function(x){return String(x.id)===String(id)});if(!p)return;var rows=(hd.entries||[]).filter(function(e){return String(e.employee_id)===String(id)}).sort(function(a,b){return String(b.work_date).localeCompare(String(a.work_date))});
 var h='<div class="sectionHead"><div><button class="btn" id="hwBack">← Trabajadores</button><h2 style="margin-top:10px">'+esc(p.full_name)+'</h2><div class="muted">'+esc(hm)+'</div></div><button class="btn primary" id="hwNew">+ Añadir día</button></div><div class="list">';
 rows.forEach(function(e){var tot=Number(e.normal_hours||0)+Number(e.overtime_hours||0)+Number(e.holiday_hours||0)+Number(e.personal_hours||0);h+='<button class="row ef7HourRow" data-hdate="'+e.work_date+'"><div><b>'+dmy(e.work_date)+'</b><small>'+(e.incident?esc(e.incident):esc(e.worksite_text||'Sin obra'))+'</small></div><div><b>'+fmt(tot)+' h</b><small>Ord '+fmt(e.normal_hours)+' · Extra '+fmt(e.overtime_hours)+' · Fest '+fmt(e.holiday_hours)+'</small></div></button>'});h+='</div>';$('#content').innerHTML=h;$('#hwBack').onclick=renderHours;$('#hwNew').onclick=function(){editHour(p.id,null)};$$('[data-hdate]').forEach(function(b){b.onclick=function(){editHour(p.id,rows.find(function(x){return x.work_date===b.dataset.hdate}))}})
}
function editHour(pid,e){
 var b=monthBounds(hm),date=e?e.work_date:(today()<b.end?today():b.end);
 var m=showModal(e?'Editar día':'Añadir día','<div class="ef7Form"><label>Fecha<input id="edDate" type="date" min="'+b.start+'" max="'+b.end+'" value="'+date+'"></label><label>Ordinarias<input id="edN" type="number" step=".5" min="0" value="'+Number(e&&e.normal_hours||0)+'"></label><label>Extra<input id="edE" type="number" step=".5" min="0" value="'+Number(e&&e.overtime_hours||0)+'"></label><label>Festivo<input id="edF" type="number" step=".5" min="0" value="'+Number(e&&e.holiday_hours||0)+'"></label><label>Personal<input id="edP" type="number" step=".5" min="0" value="'+Number(e&&e.personal_hours||0)+'"></label><label>Incidencia<select id="edI"><option value="">Ninguna</option><option value="vacation">Vacaciones</option><option value="sick_leave">Baja / IT</option><option value="absence">Ausencia</option><option value="personal">Personal</option></select></label><label class="wide">Obra<input id="edW" value="'+esc(e&&e.worksite_text||'')+'"></label><label class="wide">Observaciones<textarea id="edO">'+esc(e&&e.notes||'')+'</textarea></label><div class="wide ef7ModalActions">'+(e?'<button class="btn badBtn" id="edDel">Eliminar</button>':'')+'<button class="btn primary" id="edSave">Guardar</button></div><div id="edMsg" class="msg wide"></div></div>');
 if(e&&e.incident)m.querySelector('#edI').value=e.incident;
 m.querySelector('#edSave').onclick=async function(){var r=await api('/time/save',{employee_id:pid,work_date:m.querySelector('#edDate').value,normal_hours:+m.querySelector('#edN').value,overtime_hours:+m.querySelector('#edE').value,holiday_hours:+m.querySelector('#edF').value,personal_hours:+m.querySelector('#edP').value,incident:m.querySelector('#edI').value,worksite_text:m.querySelector('#edW').value,notes:m.querySelector('#edO').value});if(!r.ok){m.querySelector('#edMsg').textContent=r.error||'Error';return}closeModal();await loadHours();workerHours(pid)};
 if(m.querySelector('#edDel'))m.querySelector('#edDel').onclick=async function(){if(!confirm('¿Eliminar este registro?'))return;var r=await api('/time/delete',{employee_id:pid,work_date:e.work_date});if(!r.ok)return alert(r.error);closeModal();await loadHours();workerHours(pid)}
}

/* ACCESOS */
async function renderWorkers(){
 head('Trabajadores','Plantilla y accesos');loading();var z=await api('/access/list');if(!z.ok)return fail(z.error);var items=z.items||[];
 $('#content').innerHTML='<div class="sectionHead"><div><h2>Trabajadores y accesos</h2><div class="muted">PIN, sesiones y suspensión de acceso.</div></div><input id="acSearch" class="search" placeholder="Buscar trabajador…"></div><div id="acList" class="ef7AccessList"></div>';
 function draw(){var q=$('#acSearch').value.trim().toLowerCase(),a=items.filter(function(x){return String(x.full_name||'').toLowerCase().includes(q)}),h='';a.forEach(function(x){var locked=x.locked_until&&new Date(x.locked_until)>new Date(),has=!!x.has_access;h+='<div class="card ef7AccessCard"><div class="ef7AccessTop"><div><b>'+esc(x.full_name)+'</b><small>'+(x.role==='admin'?'Administrador':'Trabajador')+' · '+esc(x.dni_nie||'')+'</small></div>'+(!has?pill('warn','SIN ACCESO'):locked?pill('bad','SUSPENDIDO'):pill('ok','ACTIVO'))+'</div><div class="ef7AccessMeta"><span>Usuario: <b>'+esc(x.username||'—')+'</b></span><span>Sesiones: <b>'+Number(x.active_sessions||0)+'</b></span></div>'+(has?'<div class="actions"><button class="btn" data-aa="pin" data-id="'+x.profile_id+'" data-name="'+esc(x.full_name)+'">Cambiar PIN</button><button class="btn" data-aa="revoke" data-id="'+x.profile_id+'">Cerrar sesiones</button><button class="btn '+(locked?'primary':'badBtn')+'" data-aa="'+(locked?'reactivate':'suspend')+'" data-id="'+x.profile_id+'">'+(locked?'Reactivar':'Suspender acceso')+'</button></div>':'')+'</div>'});$('#acList').innerHTML=h}
 $('#acSearch').oninput=draw;draw();$('#acList').onclick=async function(e){var b=e.target.closest('[data-aa]');if(!b)return;var a=b.dataset.aa,id=b.dataset.id;if(a==='pin'){var pin=prompt('Nuevo PIN de 6 cifras para '+b.dataset.name+':');if(pin==null)return;if(!/^\d{6}$/.test(pin))return alert('El PIN debe tener 6 cifras');var r=await api('/access/action',{profile_id:id,action:'reset_pin',pin:pin});if(!r.ok)return alert(r.error);alert('PIN cambiado. Las sesiones anteriores se han cerrado.');return renderWorkers()}if(a==='revoke'&&!confirm('¿Cerrar todas sus sesiones abiertas?'))return;if(a==='suspend'&&!confirm('¿Suspender su acceso a la app?'))return;var r2=await api('/access/action',{profile_id:id,action:a});if(!r2.ok)return alert(r2.error);renderWorkers()}
}

/* PRECIO HORA */
async function renderRates(){
 head('Precio hora obra','Calculadora de costes');loading();var z=await api('/hour/settings');if(!z.ok)return fail(z.error);var c=Object.assign({base_monthly_gross:2060.39,monthly_normal_hours:160,extra_hour:15.89,festive_hour:16.63,night_hour:1.27,half_diet:17.98,full_diet:35.98,employer_pct:37.3,indirect_pct:15,profit_pct:20,fuel_price:1.9,fuel_consumption:8.5},z.item||{});
 $('#content').innerHTML='<div class="hero"><div><h1>Precio hora obra</h1><p>Coste real y precio recomendado.</p></div></div><div class="ef7RateGrid"><div class="card"><h3>Datos de la obra</h3><div class="ef7Form"><label>Operarios<input id="rw" type="number" value="1" min="1"></label><label>Días<input id="rd" type="number" value="20"></label><label>Horas/día<input id="rh" type="number" value="8" step=".5"></label><label>Extra/día<input id="re" type="number" value="0" step=".5"></label><label>Nº sábados<input id="rs" type="number" value="0"></label><label>Horas/sábado<input id="rsh" type="number" value="7" step=".5"></label><label>Nocturnas totales<input id="rn" type="number" value="0" step=".5"></label><label>Medias dietas<input id="rm" type="number" value="0"></label><label>Dietas completas<input id="rf" type="number" value="0"></label><label>Kilómetros<input id="rk" type="number" value="0"></label><label>Beneficio %<input id="rp" type="number" value="'+c.profit_pct+'"></label></div></div><div class="card ef7RateResult"><small>PRECIO RECOMENDADO</small><strong id="ro">—</strong><div class="ef7RateRows"><span>Coste real/h <b id="rch">—</b></span><span>Precio con beneficio <b id="rpr">—</b></span><span>Coste total <b id="rt">—</b></span><span>Facturación <b id="rb">—</b></span><span>Beneficio <b id="rbe">—</b></span></div></div></div><details class="card" style="margin-top:12px"><summary><b>Costes base</b></summary><div class="ef7Form" style="margin-top:12px"><label>Nómina base/mes<input id="cb" type="number" value="'+c.base_monthly_gross+'"></label><label>Horas/mes<input id="cmh" type="number" value="'+c.monthly_normal_hours+'"></label><label>Hora extra<input id="ce" type="number" value="'+c.extra_hour+'"></label><label>Hora festiva<input id="cf" type="number" value="'+c.festive_hour+'"></label><label>Plus nocturno<input id="cn" type="number" value="'+c.night_hour+'"></label><label>Media dieta<input id="ch" type="number" value="'+c.half_diet+'"></label><label>Dieta completa<input id="cfd" type="number" value="'+c.full_diet+'"></label><label>Coste empresa %<input id="cem" type="number" value="'+c.employer_pct+'"></label><label>Gastos generales %<input id="ci" type="number" value="'+c.indirect_pct+'"></label><label>Combustible €/L<input id="cfl" type="number" value="'+c.fuel_price+'"></label><label>Consumo L/100km<input id="cc" type="number" value="'+c.fuel_consumption+'"></label><button class="btn primary wide" id="saveRate">Guardar costes base</button></div></details>';
 function v(id){return Number($('#'+id).value||0)}function calc(){var days=v('rd'),w=Math.max(1,v('rw')),normal=days*v('rh'),extra=days*v('re'),fest=v('rs')*v('rsh'),prod=normal+extra+fest,base=v('cb')*(normal/Math.max(1,v('cmh'))),gross=base+extra*v('ce')+fest*v('cf')+v('rn')*v('cn')+v('rm')*v('ch')+v('rf')*v('cfd'),real=gross*(1+v('cem')/100)*(1+v('ci')/100),fuel=v('rk')*v('cc')/100*v('cfl'),hours=prod*w,total=real*w+fuel,cost=hours?total/hours:0,price=cost*(1+v('rp')/100),offer=Math.ceil(price*2)/2,bill=offer*hours,benefit=Math.max(0,bill-total);$('#rch').textContent=euro(cost)+'/h';$('#rpr').textContent=euro(price)+'/h';$('#ro').textContent=euro(offer)+'/h';$('#rt').textContent=euro(total);$('#rb').textContent=euro(bill);$('#rbe').textContent=euro(benefit)}
 $$('input').forEach(function(x){if(x.id&&(x.id[0]==='r'||x.id[0]==='c'))x.oninput=calc});calc();
 $('#saveRate').onclick=async function(){var r=await api('/hour/save',{base_monthly_gross:v('cb'),monthly_normal_hours:v('cmh'),extra_hour:v('ce'),festive_hour:v('cf'),night_hour:v('cn'),half_diet:v('ch'),full_diet:v('cfd'),employer_pct:v('cem'),indirect_pct:v('ci'),profit_pct:v('rp'),fuel_price:v('cfl'),fuel_consumption:v('cc'),default_vehicles:1});if(!r.ok)return alert(r.error);alert('Costes guardados')}
}

/* DOCUMENTOS DRIVE ACTUALES */
var docsCache=null;
async function docs(force){if(docsCache&&!force)return docsCache;var z=await api('/docs/list');if(!z.ok)throw Error(z.error||'No se pudo cargar Drive');docsCache=z;return z}
function docState(x){if(x.no_expiry||!x.expiry_date)return['ok','Vigente'];var a=new Date(today()+'T00:00:00'),b=new Date(x.expiry_date+'T00:00:00'),d=Math.round((b-a)/86400000);if(d<=0)return['bad','Caducado'];if(d<=30)return['warn','Próximo'];return['ok','Vigente']}
function docCard(x){var s=docState(x);return '<div class="card ef7Doc"><div class="docName">'+esc(x.file_name)+'</div><div class="docMeta"><span>'+(x.issue_date?'Emisión: '+dmy(x.issue_date):'Sin fecha de emisión')+'</span><span>'+(x.expiry_date?'Caducidad: '+dmy(x.expiry_date):(x.no_expiry?'Sin caducidad':'Sin caducidad indicada'))+'</span></div><div class="ef7DocFoot">'+pill(s[0],s[1])+(x.cloud_available?'<button class="btn" data-cdoc="'+x.file_id+'" data-cname="'+esc(x.file_name)+'">Abrir</button>':'<span class="state info">Drive actual · pendiente nube</span>')+'</div></div>'}
async function openDoc(id,name){var z=await api('/docs/url',{file_id:id,download:false});if(!z.ok)return alert(z.error||'No se pudo abrir');window.open(z.url,'_blank','noopener')}
function wireDoc(){$$('[data-cdoc]').forEach(function(b){b.onclick=function(){openDoc(b.dataset.cdoc,b.dataset.cname)}})}
async function renderCAE(){
 head('CAE / PRL','Inventario actual de Drive · solo lectura');loading();
 try{var z=await docs(),items=(z.items||[]).filter(function(x){return x.scope==='employee'}),by=new Map();items.forEach(function(x){var k=x.owner_name||'Sin trabajador';if(!by.has(k))by.set(k,[]);by.get(k).push(x)});var h='<div class="hero"><div><h1>CAE / PRL</h1><p>Documentos detectados actualmente en Drive.</p></div><span class="pill">SOLO LECTURA</span></div><div class="notice">Este listado ya no usa el espejo antiguo. “Pendiente nube” significa que el archivo existe en Drive pero aún no hay copia web para abrirlo desde el móvil.</div><div class="sectionHead"><div class="muted">Última lectura: '+(z.last_updated?new Date(z.last_updated).toLocaleString('es-ES'):'—')+'</div><button class="btn" id="docRefresh">Actualizar</button></div><div class="caeWorkerList">';
 Array.from(by.entries()).sort(function(a,b){return a[0].localeCompare(b[0],'es')}).forEach(function(g){h+='<details class="caeWorker"><summary><div class="caeWorkerName">'+esc(g[0])+'<small>'+g[1].length+' documentos</small></div></summary><div class="caeWorkerDocs">'+g[1].map(docCard).join('')+'</div></details>'});h+='</div>';$('#content').innerHTML=h;$('#docRefresh').onclick=function(){docsCache=null;renderCAE()};wireDoc()
 }catch(e){fail(e.message)}
}
async function renderCompany(){
 head('Empresa','Documentación actual por carpetas');loading();
 try{var z=await docs(),items=(z.items||[]).filter(function(x){return x.scope==='company'}),by=new Map();items.forEach(function(x){var f=(x.folder_path||'Sin carpeta').split('/')[0]||'Sin carpeta';if(!by.has(f))by.set(f,[]);by.get(f).push(x)});var h='<div class="hero"><div><h1>Empresa</h1><p>Documentación actual separada por carpetas.</p></div><span class="pill">SOLO LECTURA</span></div><div class="caeWorkerList">';Array.from(by.entries()).sort(function(a,b){return a[0].localeCompare(b[0],'es')}).forEach(function(g){h+='<details class="caeWorker"><summary><div class="caeWorkerName">📁 '+esc(g[0])+'<small>'+g[1].length+' archivos</small></div></summary><div class="caeWorkerDocs">'+g[1].map(docCard).join('')+'</div></details>'});h+='</div>';$('#content').innerHTML=h;wireDoc()
 }catch(e){fail(e.message)}
}

var st=document.createElement('style');st.textContent='.ef7Modal{position:fixed;z-index:100000;inset:0;background:#000b;display:flex;align-items:flex-end;justify-content:center;padding:12px}.ef7Modal.hidden{display:none}.ef7ModalBox{width:min(680px,100%);max-height:92vh;overflow:auto;background:#0b1710;border:1px solid #33503a;border-radius:18px;padding:14px}.ef7ModalHead{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.ef7Form{display:grid;grid-template-columns:1fr 1fr;gap:9px}.ef7Form label{display:grid;gap:5px;color:#91a496;font-size:11px;font-weight:800}.ef7Form input,.ef7Form select,.ef7Form textarea{width:100%;background:#071009;color:#eef7ef;border:1px solid #314737;border-radius:10px;padding:11px}.ef7Form textarea{min-height:75px}.ef7Form .wide{grid-column:1/-1}.ef7ModalActions{display:flex;justify-content:space-between;gap:8px}.badBtn{border-color:#703640!important;background:#34161a!important;color:#ffadb5!important}.ef7RowActions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.ef7WorkerCards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.ef7WorkerCard{border:1px solid #26382c;border-radius:14px;background:#09140d;color:#eef7ef;padding:14px;text-align:left;display:flex;justify-content:space-between;gap:10px;align-items:center}.ef7WorkerCard small,.ef7AccessCard small{display:block;color:#91a496;margin-top:4px}.ef7WorkerCard strong{font-size:18px;color:#8bea99;white-space:nowrap}.ef7HourRow{cursor:pointer;text-align:left}.ef7AccessList{display:grid;gap:9px}.ef7AccessTop{display:flex;justify-content:space-between;gap:10px}.ef7AccessMeta{display:flex;gap:12px;flex-wrap:wrap;color:#91a496;font-size:11px;margin:10px 0}.ef7RateGrid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:12px}.ef7RateResult strong{display:block;font-size:38px;color:#8bea99;margin:8px 0 14px}.ef7RateRows{display:grid;gap:8px}.ef7RateRows span{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #203027;padding-top:8px}.ef7DocFoot{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:10px}.ef7Doc{margin:0}.ef7Month{max-width:180px}@media(max-width:760px){.ef7Form{grid-template-columns:1fr}.ef7Form .wide{grid-column:auto}.ef7WorkerCards{grid-template-columns:1fr}.ef7RateGrid{grid-template-columns:1fr}.ef7RowActions{justify-content:flex-start}.ef7Modal{padding:0}.ef7ModalBox{border-radius:18px 18px 0 0;max-height:96vh}}';document.head.appendChild(st);

function wire(){bindPage('punches',renderPunches);bindPage('hours',renderHours);bindPage('workers',renderWorkers);bindPage('rates',renderRates);bindPage('cae',renderCAE);bindPage('company',renderCompany);captureCards()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(wire,250)});else setTimeout(wire,250);
})();