plugins {
    id 'com.android.application'
}

android {
    namespace 'com.carmonitor.demo'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carmonitor.demo'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '3.0-v8-custom-ui'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
