plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bryu.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bryu.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.2-test'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.mlkit:translate:17.0.3'
}

// BRYU AndroidX build
