plugins {
    id 'com.android.application'
}

android {
    namespace 'com.electrofelec.admin'
    compileSdk 35

    defaultConfig {
        applicationId 'com.electrofelec.admin'
        minSdk 23
        targetSdk 35
        versionCode 17
        versionName '2.11-admin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
