from pathlib import Path

p=Path('android-admin/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')

s=s.replace('Electrofelec Admin v2.7','Electrofelec Admin v2.8')
s=s.replace('v2.7 · Diseño Gestor móvil','v2.8 · Diseño Gestor móvil')
s=s.replace('APP v2.7','APP v2.8')
s=s.replace('· APP v2.7','· APP v2.8')

old="else if(name==='Payroll'){setTimeout(g27LoadMyPayroll,80)}else if(name==='More')"
new="else if(name==='Payroll'){setTimeout(g28LoadPayrollPage,80)}else if(name==='More')"
if old not in s: raise SystemExit('No se encontró hook Payroll v2.7')
s=s.replace(old,new,1)

css=r'''
/* ===== Admin v2.8 · firma propia + nóminas y firmas empresa ===== */
.g28-sign{background:#57d51d!important;color:#071006!important;border-color:#69ee2f!important;font-weight:950}.g28-admin-pay{border-color:#315b3b!important;background:linear-gradient(150deg,#0d2014,#08120c)!important}.g28-pay-toolbar{display:grid;grid-template-columns:100px minmax(130px,1fr) auto;gap:8px;align-items:end}.g28-pay-toolbar label{font-size:10px;color:var(--muted);font-weight:800}.g28-pay-toolbar select{margin-top:4px}.g28-pay-actions-top{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.g28-pay-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.g28-pay-kpi{border:1px solid #293b2e;border-radius:11px;background:#09150d;padding:10px}.g28-pay-kpi span{display:block;font-size:9px;color:var(--muted);text-transform:uppercase;font-weight:850}.g28-pay-kpi b{display:block;font-size:22px;margin-top:4px}.g28-admin-list{display:grid;gap:7px}.g28-admin-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border:1px solid #25362a;border-radius:11px;background:#09140c;padding:10px}.g28-admin-row.signed{border-color:#2d6a3b;background:#0c1e12}.g28-admin-row.pending{border-color:#67551f;background:#211b0c}.g28-admin-row.missing{opacity:.78}.g28-admin-name{font-size:13px;font-weight:900}.g28-admin-dni{font-size:9px;color:var(--muted);margin-top:2px}.g28-admin-state{font-size:10px;font-weight:900;margin-top:5px}.g28-admin-buttons{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.g28-admin-buttons .btn{min-height:36px}.g28-sign-wrap{border:1px solid #324639;border-radius:12px;background:#fff;padding:7px;margin-top:10px}.g28-sign-canvas{display:block;width:100%;height:190px;touch-action:none;background:#fff;border-radius:8px}.g28-sign-help{font-size:10px;color:var(--muted);margin:8px 0}.g28-upload-map{display:grid;gap:7px;max-height:52vh;overflow:auto;margin-top:10px}.g28-upload-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,.8fr);gap:8px;align-items:center;border:1px solid #2a3a2f;border-radius:9px;padding:8px}.g28-upload-file{font-size:11px;font-weight:800;overflow-wrap:anywhere}.g28-page-row{display:grid;grid-template-columns:52px minmax(0,1fr);gap:8px;align-items:center;border-bottom:1px solid #243027;padding:7px 0}.g28-page-row:last-child{border-bottom:0}.g28-page-num{font-weight:900;color:#9ddda7}.g28-progress{border:1px solid #304238;border-radius:10px;padding:10px;margin-top:10px;color:#a9cbb0}.g28-hidden-input{display:none!important}
@media(max-width:700px){.g28-pay-toolbar{grid-template-columns:1fr 1fr}.g28-pay-toolbar .g28-refresh{grid-column:1/-1;width:100%}.g28-admin-row{grid-template-columns:1fr}.g28-admin-buttons{justify-content:flex-start}.g28-pay-kpis{grid-template-columns:repeat(3,1fr)}.g28-upload-row{grid-template-columns:1fr}.g28-pay-actions-top .btn{flex:1 1 calc(50% - 7px)}}
@media(max-width:430px){.g28-pay-kpis{grid-template-columns:1fr}.g28-pay-actions-top .btn{flex:1 1 100%}}
'''
if 'Admin v2.8 · firma propia' not in s:
    pos=s.rfind('</style>')
    if pos<0: raise SystemExit('No se encontró </style>')
    s=s[:pos]+css+s[pos:]

js=r'''

/* ===== Admin v2.8 · firma propia + gestión de nóminas ===== */
const G28_ADMINPAY='https://kbdmraxjfgtttopsyfuy.supabase.co/functions/v1/electrofelec-payroll-admin-mobile';
const g28PrevMonth=(()=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return d})();
let g28PayYear=g28PrevMonth.getFullYear(),g28PayMonth=g28PrevMonth.getMonth()+1,g28AdminItems=[],g28UploadFiles=[],g28CombinedState=null,g28SigDirty=false;

function g28MadridDate(){return typeof g20MadridToday==='function'?g20MadridToday():new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function g28CanSign(x){return !x?.receipt?.signed_at&&(!x?.available_date||g28MadridDate()>=String(x.available_date).slice(0,10))}
function g28FmtDateTime(v){try{return new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(e){return'—'}}
function g28SafeName(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,70)||'Trabajador'}
function g28Norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function g28Compact(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
async function g28AdminJson(path,body={}){try{const r=await fetch(G28_ADMINPAY+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({session_token:token},body)),cache:'no-store'});const z=await r.json().catch(()=>({ok:false,error:'Respuesta no válida'}));if(!r.ok&&z.ok!==false)z.ok=false;return z}catch(e){return{ok:false,error:'Sin conexión'}}}
async function g28UploadOne(file,employeeId,batch=''){const fd=new FormData();fd.append('session_token',token);fd.append('file',file);fd.append('employee_id',employeeId);fd.append('year',String(g28PayYear));fd.append('month',String(g28PayMonth));if(batch)fd.append('source_batch_name',batch);const r=await fetch(G28_ADMINPAY+'/upload',{method:'POST',body:fd});const z=await r.json().catch(()=>({ok:false,error:'Respuesta no válida'}));if(!r.ok||!z.ok)throw Error(z.error||'No se pudo subir la nómina');return z}

async function g28LoadPayrollPage(){await Promise.allSettled([g28LoadMyPayroll(),g28LoadAdminPayroll()])}

function g28EnsureMyPayroll(){let card=$('g27MyPayroll');if(card)return card;const sec=$('secPayroll');if(!sec)return null;card=document.createElement('div');card.id='g27MyPayroll';card.className='card g27-personal-card';sec.prepend(card);return card}
async function g28LoadMyPayroll(){const card=g28EnsureMyPayroll();if(!card)return;card.innerHTML='<div class="g27-head"><div><div class="g26-eyebrow">PERSONAL</div><h2>Mis nóminas</h2><div class="muted small">Tu nómina personal y firma de recepción</div></div><button id="g28PayRefreshMine" class="g26-icon-btn">↻</button></div><div id="g28MineBody"><div class="loading">Cargando tus nóminas…</div></div>';$('g28PayRefreshMine').onclick=g28LoadMyPayroll;const body=$('g28MineBody'),z=await g27Pay('/worker/list');if(!z.ok){body.innerHTML='<div class="g20-errorbox">'+esc(z.error||'No se pudieron cargar tus nóminas')+'</div>';return}const items=z.items||[];body.innerHTML='<div class="g27-pay-list">'+(items.map(x=>{const signed=!!x.receipt?.signed_at,can=g28CanSign(x);return '<div class="g27-pay-row"><div class="g27-pay-icon">€</div><div><div class="g27-pay-title">'+esc(g27MonthName(x.payroll_month)+' '+x.payroll_year)+'</div><div class="g27-pay-meta">Puesta a disposición: '+g20Date(x.available_date)+' · <span class="'+(signed?'g27-signed':'g27-pending')+'">'+(signed?'Firmada '+g28FmtDateTime(x.receipt.signed_at):can?'Pendiente de firma':'Pendiente · aún no disponible')+'</span></div><div class="g27-pay-actions"><button class="btn secondary" data-g28mine="view" data-id="'+x.id+'">Ver nómina</button><button class="btn secondary" data-g28mine="download" data-id="'+x.id+'">Descargar</button>'+(signed?'<button class="btn secondary" data-g28mine="certificate" data-id="'+x.id+'">Certificado</button>':can?'<button class="btn g28-sign" data-g28mine="sign" data-id="'+x.id+'">FIRMAR RECEPCIÓN</button>':'')+'</div></div></div>'}).join('')||'<div class="g27-empty">Todavía no tienes nóminas personales publicadas.</div>')+'</div>';$$('[data-g28mine]').forEach(b=>b.onclick=()=>{const x=items.find(q=>String(q.id)===String(b.dataset.id));if(b.dataset.g28mine==='sign')g28OpenSignature(x);else g27OpenPayroll(b.dataset.id,b.dataset.g28mine)})}

function g28OpenSignature(doc){if(!doc?.id)return;g28SigDirty=false;openModal('Firmar recepción · '+g27MonthName(doc.payroll_month)+' '+doc.payroll_year,`<div class="notice">Confirma que has recibido y podido consultar tu nómina. La firma y la hora real quedarán guardadas en el certificado de recepción.</div><div class="g28-sign-wrap"><canvas id="g28SigCanvas" class="g28-sign-canvas"></canvas></div><div class="g28-sign-help">Firma dentro del recuadro con el dedo o el ratón.</div><div id="g28SigMsg" class="notice" style="display:none"></div><div class="footer"><button id="g28SigClear" class="btn secondary">Borrar firma</button><button class="btn" onclick="closeModal()">Cancelar</button><button id="g28SigSave" class="btn primary">Firmar recepción</button></div>`);setTimeout(()=>g28BindSignature(doc),30)}
function g28BindSignature(doc){const c=$('g28SigCanvas');if(!c)return;const r=c.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);c.width=Math.max(300,Math.round(r.width*dpr));c.height=Math.max(160,Math.round(r.height*dpr));const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);ctx.strokeStyle='#101010';ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';let down=false;const pos=e=>{const b=c.getBoundingClientRect(),p=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:p.clientX-b.left,y:p.clientY-b.top}};const start=e=>{e.preventDefault();down=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!down)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();g28SigDirty=true};const end=e=>{if(down){e.preventDefault();down=false}};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);$('g28SigClear').onclick=()=>{ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);g28SigDirty=false};$('g28SigSave').onclick=()=>g28SaveSignature(doc,c)}
async function g28SaveSignature(doc,c){const msg=$('g28SigMsg'),btn=$('g28SigSave');if(!g28SigDirty){msg.style.display='block';msg.textContent='Primero dibuja tu firma.';return}btn.disabled=true;btn.textContent='Guardando firma…';msg.style.display='block';msg.textContent='Generando certificado…';const z=await g27Pay('/worker/sign',{document_id:doc.id,signature_data_url:c.toDataURL('image/png')});if(!z.ok){btn.disabled=false;btn.textContent='Firmar recepción';msg.textContent=z.error||'No se pudo firmar';return}msg.textContent='✓ Firma guardada y certificado generado';setTimeout(()=>{closeModal();g28LoadPayrollPage()},500)}

function g28EnsureAdminPayroll(){let card=$('g28PayrollAdmin');if(card)return card;const sec=$('secPayroll');if(!sec)return null;card=document.createElement('div');card.id='g28PayrollAdmin';card.className='card g28-admin-pay';const mine=$('g27MyPayroll');if(mine?.nextSibling)sec.insertBefore(card,mine.nextSibling);else sec.appendChild(card);return card}
function g28MonthOptions(){return Array.from({length:12},(_,i)=>'<option value="'+(i+1)+'" '+(g28PayMonth===i+1?'selected':'')+'>'+g27MonthName(i+1)+'</option>').join('')}
function g28YearOptions(){const y=new Date().getFullYear();return [y-2,y-1,y,y+1].map(v=>'<option value="'+v+'" '+(v===g28PayYear?'selected':'')+'>'+v+'</option>').join('')}
async function g28LoadAdminPayroll(){const card=g28EnsureAdminPayroll();if(!card)return;card.innerHTML='<div class="g27-head"><div><div class="g26-eyebrow">EMPRESA</div><h2>Nóminas y firmas</h2><div class="muted small">El mismo control de publicación, firmas y certificados del Gestor PC</div></div></div><div class="g28-pay-toolbar"><label>Año<select id="g28PayYear">'+g28YearOptions()+'</select></label><label>Mes<select id="g28PayMonth">'+g28MonthOptions()+'</select></label><button id="g28PayRefresh" class="btn secondary g28-refresh">↻ Actualizar</button></div><div class="g28-pay-actions-top"><button id="g28CombinedImport" class="btn primary">Seleccionar PDF conjunto</button><button id="g28SeparateImport" class="btn secondary">Importar PDFs separados</button><button id="g28CombinedCert" class="btn primary">PDF conjunto certificados</button><input id="g28CombinedInput" class="g28-hidden-input" type="file" accept="application/pdf,.pdf"><input id="g28SeparateInput" class="g28-hidden-input" type="file" accept="application/pdf,.pdf" multiple></div><div id="g28AdminPayBody"><div class="loading">Cargando estado del mes…</div></div>';$('g28PayYear').onchange=e=>{g28PayYear=Number(e.target.value);g28LoadAdminPayroll()};$('g28PayMonth').onchange=e=>{g28PayMonth=Number(e.target.value);g28LoadAdminPayroll()};$('g28PayRefresh').onclick=g28LoadAdminPayroll;$('g28SeparateImport').onclick=()=>$('g28SeparateInput').click();$('g28CombinedImport').onclick=()=>$('g28CombinedInput').click();$('g28SeparateInput').onchange=e=>g28PrepareSeparate([...e.target.files]);$('g28CombinedInput').onchange=e=>{const f=e.target.files?.[0];if(f)g28PrepareCombined(f)};$('g28CombinedCert').onclick=g28DownloadCombinedCert;const body=$('g28AdminPayBody'),z=await g28AdminJson('/list',{year:g28PayYear,month:g28PayMonth});if(!z.ok){body.innerHTML='<div class="g20-errorbox">'+esc(z.error||'No se pudo cargar el mes')+'</div>';return}g28AdminItems=z.items||[];g28RenderAdminPayroll()}
function g28RenderAdminPayroll(){const body=$('g28AdminPayBody');if(!body)return;const published=g28AdminItems.filter(x=>x.document).length,signed=g28AdminItems.filter(x=>x.status==='signed').length,pending=published-signed;body.innerHTML='<div class="g28-pay-kpis"><div class="g28-pay-kpi"><span>Publicadas</span><b>'+published+'</b></div><div class="g28-pay-kpi"><span>Firmadas</span><b class="good">'+signed+'</b></div><div class="g28-pay-kpi"><span>Pendientes</span><b class="'+(pending?'warn':'good')+'">'+pending+'</b></div></div><div class="muted small" style="margin:8px 0 7px"><b>Nóminas de '+esc(g27MonthName(g28PayMonth)+' '+g28PayYear)+'</b> · nómina y certificado</div><div class="g28-admin-list">'+g28AdminItems.map(x=>{const st=x.status==='signed'?'signed':x.document?'pending':'missing',label=st==='signed'?'Firmada':st==='pending'?'Pendiente de firma':'Sin nómina',when=x.receipt?.signed_at?g28FmtDateTime(x.receipt.signed_at):'—';return '<div class="g28-admin-row '+st+'"><div><div class="g28-admin-name">'+esc(x.full_name)+'</div><div class="g28-admin-dni">'+esc(x.dni_nie||'Sin DNI/NIE')+' · '+(x.role==='admin'?'Administrador':'Trabajador')+'</div><div class="g28-admin-state">'+esc(label)+(st==='signed'?' · '+esc(when):x.document?' · disponible '+g20Date(x.document.available_date):'')+'</div></div><div class="g28-admin-buttons">'+(x.document?'<button class="btn secondary" data-g28doc="view" data-id="'+x.document.id+'">Ver nómina</button>':'')+(x.receipt?.signed_at?'<button class="btn secondary" data-g28cert="'+x.receipt.id+'">Certificado</button>':'')+'</div></div>'}).join('')+'</div>';$$('[data-g28doc]').forEach(b=>b.onclick=()=>g28OpenAdminDoc(b.dataset.id));$$('[data-g28cert]').forEach(b=>b.onclick=()=>g28OpenAdminCert(b.dataset.g28cert))}
async function g28OpenAdminDoc(id){const z=await g28AdminJson('/url',{document_id:id,download:false});if(!z.ok||!z.url)return alert(z.error||'No se pudo abrir la nómina');window.location.href=z.url}
async function g28OpenAdminCert(id){const z=await g28AdminJson('/certificate-url',{receipt_id:id,download:false});if(!z.ok||!z.url)return alert(z.error||'No se pudo abrir el certificado');window.location.href=z.url}
async function g28DownloadCombinedCert(){const b=$('g28CombinedCert');if(b){b.disabled=true;b.textContent='Generando…'}try{const r=await fetch(G28_ADMINPAY+'/combined-certificates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_token:token,year:g28PayYear,month:g28PayMonth})});if(!r.ok){const z=await r.json().catch(()=>({}));throw Error(z.error||'No se pudo generar')}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Certificados_'+g27MonthName(g28PayMonth)+'_'+g28PayYear+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000)}catch(e){alert(e.message||String(e))}finally{if(b){b.disabled=false;b.textContent='PDF conjunto certificados'}}}

function g28GuessEmployee(fileName){const n=g28Norm(fileName),c=g28Compact(fileName);let exact=g28AdminItems.find(x=>{const d=g28Compact(x.dni_nie||'');return d.length>=6&&c.includes(d)});if(exact)return exact.id;let best=null,score=0;for(const x of g28AdminItems){const toks=g28Norm(x.full_name).split(' ').filter(t=>t.length>=3),s=toks.reduce((a,t)=>a+(n.includes(t)?1:0),0);if(s>score&&s>=2){score=s;best=x}}return best?.id||''}
function g28PersonOptions(selected=''){return '<option value="">— Selecciona persona —</option>'+g28AdminItems.map(x=>'<option value="'+x.id+'" '+(String(selected)===String(x.id)?'selected':'')+'>'+esc(x.full_name)+' · '+esc(x.dni_nie||'')+'</option>').join('')}
function g28PrepareSeparate(files){g28UploadFiles=(files||[]).filter(f=>f.name.toLowerCase().endsWith('.pdf'));if(!g28UploadFiles.length)return alert('Selecciona uno o más PDF.');openModal('Importar PDFs separados',`<div class="notice">Asocia cada PDF con su trabajador. Intento reconocerlo por DNI/NIE o nombre, pero puedes corregirlo antes de subir.</div><div class="g28-upload-map">${g28UploadFiles.map((f,i)=>'<div class="g28-upload-row"><div class="g28-upload-file">'+esc(f.name)+'</div><select data-g28map="'+i+'">'+g28PersonOptions(g28GuessEmployee(f.name))+'</select></div>').join('')}</div><div id="g28UploadMsg" class="g28-progress" style="display:none"></div><div class="footer"><button class="btn" onclick="closeModal()">Cancelar</button><button id="g28UploadSave" class="btn primary">Importar '+g28UploadFiles.length+' PDF</button></div>`);$('g28UploadSave').onclick=g28SaveSeparate}
async function g28SaveSeparate(){const maps=[...document.querySelectorAll('[data-g28map]')],jobs=maps.map(s=>({file:g28UploadFiles[Number(s.dataset.g28map)],employee:s.value}));if(jobs.some(x=>!x.employee))return alert('Asocia todos los PDF con una persona.');const btn=$('g28UploadSave'),msg=$('g28UploadMsg');btn.disabled=true;msg.style.display='block';let done=0;try{for(const j of jobs){msg.textContent='Subiendo '+(done+1)+' de '+jobs.length+' · '+j.file.name;await g28UploadOne(j.file,j.employee,'Importación PDFs separados');done++}msg.textContent='✓ '+done+' nóminas importadas';setTimeout(()=>{closeModal();g28LoadPayrollPage()},500)}catch(e){btn.disabled=false;msg.textContent='Error: '+(e.message||String(e))}}

function g28LoadScript(url,test){return new Promise((res,rej)=>{if(test())return res();const sc=document.createElement('script');sc.src=url;sc.onload=()=>test()?res():rej(Error('La librería no se inició'));sc.onerror=()=>rej(Error('No se pudo cargar la librería PDF'));document.head.appendChild(sc)})}
async function g28LoadPdfLibs(){await g28LoadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',()=>!!window.pdfjsLib);try{window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}catch(e){}await g28LoadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js',()=>!!window.PDFLib)}
function g28GuessPage(text){const n=g28Norm(text),c=g28Compact(text);let hits=g28AdminItems.filter(x=>{const d=g28Compact(x.dni_nie||'');return d.length>=6&&c.includes(d)});if(hits.length===1)return hits[0].id;let best=null,score=0,tie=false;for(const x of g28AdminItems){const toks=g28Norm(x.full_name).split(' ').filter(t=>t.length>=3),s=toks.reduce((a,t)=>a+(n.includes(t)?1:0),0);if(s>score){score=s;best=x;tie=false}else if(s===score&&s>0)tie=true}return best&&score>=2&&!tie?best.id:''}
async function g28PrepareCombined(file){if(!g28AdminItems.length){alert('Espera a que cargue la lista de trabajadores.');return}openModal('Analizando PDF conjunto','<div class="loading">Leyendo páginas y buscando DNI/NIE…</div>');try{await g28LoadPdfLibs();const buf=await file.arrayBuffer(),pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(buf),disableWorker:true}).promise,pages=[];let prev='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),tc=await page.getTextContent(),text=(tc.items||[]).map(x=>x.str||'').join(' '),guess=g28GuessPage(text)||prev;pages.push({page:i,guess,text:text.slice(0,180)});if(guess)prev=guess}g28CombinedState={file,buffer:buf,pages};closeModal();g28ShowCombinedMapping()}catch(e){closeModal();alert('No se pudo analizar el PDF conjunto: '+(e.message||String(e))+'\nPuedes usar “Importar PDFs separados”.')}}
function g28ShowCombinedMapping(){const st=g28CombinedState;if(!st)return;openModal('PDF conjunto · revisar páginas',`<div class="notice">He intentado identificar cada página por DNI/NIE y nombre. Revisa la persona asignada antes de importar. Las páginas asignadas a la misma persona se unirán en una sola nómina.</div><div class="g28-upload-map">${st.pages.map((p,i)=>'<div class="g28-page-row"><div class="g28-page-num">Pág. '+p.page+'</div><select data-g28page="'+i+'">'+g28PersonOptions(p.guess)+'</select></div>').join('')}</div><div id="g28CombinedMsg" class="g28-progress" style="display:none"></div><div class="footer"><button class="btn" onclick="closeModal()">Cancelar</button><button id="g28CombinedSave" class="btn primary">Separar e importar</button></div>`);$('g28CombinedSave').onclick=g28SaveCombined}
async function g28SaveCombined(){const st=g28CombinedState,sel=[...document.querySelectorAll('[data-g28page]')];if(!st||!sel.length)return;const assignments=sel.map(s=>s.value);if(assignments.some(x=>!x))return alert('Asocia todas las páginas con una persona.');const btn=$('g28CombinedSave'),msg=$('g28CombinedMsg');btn.disabled=true;msg.style.display='block';try{const src=await window.PDFLib.PDFDocument.load(st.buffer),groups=new Map();assignments.forEach((id,i)=>{if(!groups.has(id))groups.set(id,[]);groups.get(id).push(i)});let done=0;for(const [id,idxs] of groups){const person=g28AdminItems.find(x=>String(x.id)===String(id)),out=await window.PDFLib.PDFDocument.create(),copied=await out.copyPages(src,idxs);copied.forEach(p=>out.addPage(p));const bytes=await out.save(),name='Nomina_'+g28SafeName(person?.full_name)+'_'+g28PayYear+'-'+String(g28PayMonth).padStart(2,'0')+'.pdf',file=new File([bytes],name,{type:'application/pdf'});msg.textContent='Importando '+(++done)+' de '+groups.size+' · '+(person?.full_name||'Trabajador');await g28UploadOne(file,id,st.file.name)}msg.textContent='✓ '+groups.size+' nóminas separadas e importadas';setTimeout(()=>{g28CombinedState=null;closeModal();g28LoadPayrollPage()},600)}catch(e){btn.disabled=false;msg.textContent='Error: '+(e.message||String(e))}}
'''

if 'Admin v2.8 · firma propia + gestión de nóminas' not in s:
    pos=s.rfind('</script>')
    if pos<0: raise SystemExit('No se encontró </script>')
    s=s[:pos]+js+s[pos:]

p.write_text(s,encoding='utf-8')
print('Admin v2.8 aplicado: firma de administradores + gestión de nóminas y certificados')
